export const LOAD_TODO_ITEMS = "LOAD_TODO_ITEMS";
export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";
export const EDIT_TODO_ITEM = "EDIT_TODO_ITEM";
export const MARK_ITEM_DONE = "MARK_ITEM_DONE";
